name: Build and publish GitLab Components
on:
  workflow_dispatch:
    inputs: 
      releaseTag: # Accessible through ${{ inputs.releaseTag }}
        description: 'Required fcli release tag for which to build and release Docker images'
        required: true
        type: string
      doPublish:
        description: 'Boolean indicating whether images should be published to Docker Hub'
        required: true
        type: boolean
          
jobs:
  update-gitlab-components:
    runs-on: ubuntu-latest
    steps:
        - name: Check-out source code
          uses: actions/checkout@v4
          with:
            ref: ${{ inputs.releaseTag }}
            fetch-tags: true
            
        - name: Update GitLab fcli components repository
          shell: bash
          run: |
            releaseTag=${{inputs.releaseTag}}
            version=${releaseTag#v}
            gitUrl=https://github:${{ secrets.GL_PROJECT_TOKEN }}@gitlab.com/Fortify/components/fcli.git
            git clone $gitUrl fcli-components
            cp -a fcli-other/fcli-ci-integration/gitlab/* fcli-other/fcli-ci-integration/gitlab/.gitlab-ci.yml fcli-components
            cd fcli-components
            sed -e "s/__VERSION__/${version}/g" -i README.md templates/*.yml
            if [[ `git status --porcelain` ]]; then
              echo "Changes detected"
              git config user.name github-actions
              git config user.email github-actions@fortify.com
              git add .
              git commit -m "Update for fcli ${releaseTag}"
              git tag -f -a -m "Auto-generated tag" ${version}
              if ${{inputs.doPublish}}; then
                echo "Pushing updates"
                git push origin :refs/tags/${version} # Delete existing tag
                git push $gitUrl --follow-tags
              fi
            else
              echo "No changes detected, skipping update"
            fi